name: Jekyll site CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future && grep -R 'href=\"/' ./_site | cut -f'1' -d':' | uniq | xargs sed -i  's|href=\"/|href=\"/${{ env.targetdir }}/|'"
    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: _site/
